services:
  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: ${DEVBOX_POSTGRES172_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${DEVBOX_POSTGRES172_POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${DEVBOX_POSTGRES172_POSTGRES_DB:-dev}
    volumes:
      - postgres172_db_data:/var/lib/postgresql/data
    networks:
      postgres172_network_local:
        aliases:
          - db.postgres172.devbox.local
    hostname: db.postgres172.devbox.local
    ports:
      - ${DEVBOX_POSTGRES172_DB_EXPORT_PORT:-16442}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
  pgadmin:
    image: dpage/pgadmin4:8
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEVBOX_POSTGRES172_PGADMIN_EMAIL:-pgadmin4@devbox.local}
      PGADMIN_DEFAULT_PASSWORD: ${DEVBOX_POSTGRES172_PGADMIN_PASSWORD:-password}
    networks:
      postgres172_network_local:
        aliases:
          - pgadmin.postgres172.devbox.local
    hostname: pgadmin.postgres172.devbox.local
    ports:
      - ${DEVBOX_POSTGRES172_PGADMIN_EXPORT_PORT:-16443}:80
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "80"]
      start_period: 100s
      interval: 3s
      timeout: 1s
      retries: 60
  pgweb:
    image: sosedoff/pgweb:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DEVBOX_POSTGRES172_POSTGRES_USER:-postgres}:${DEVBOX_POSTGRES172_POSTGRES_PASSWORD:-password}@db.postgres172.devbox.local:5432/${DEVBOX_POSTGRES172_POSTGRES_DB:-dev}?sslmode=disable
    networks:
      postgres172_network_local:
        aliases:
          - pgweb.postgres172.devbox.local
    hostname: pgweb.postgres172.devbox.local
    ports:
      - ${DEVBOX_POSTGRES172_PGWEB_EXPORT_PORT:-16444}:8081
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 3s
      timeout: 1s
      retries: 20
  dbgate:
    image: dbgate/dbgate:alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONNECTIONS: postgres1
      ENGINE_postgres1: postgres@dbgate-plugin-postgres
      LABEL_postgres1: db.postgres172.devbox.local
      SERVER_postgres1: db.postgres172.devbox.local
      PORT_postgres1: 5432
      USER_postgres1: ${DEVBOX_POSTGRES172_POSTGRES_USER:-postgres}
      PASSWORD_postgres1: ${DEVBOX_POSTGRES172_POSTGRES_PASSWORD:-password}
    networks:
      postgres172_network_local:
        aliases:
          - dbgate.postgres172.devbox.local
    hostname: dbgate.postgres172.devbox.local
    ports:
      - ${DEVBOX_POSTGRES172_DBGATE_EXPORT_PORT:-16445}:3000
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "3000"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  postgres172_db_data:

networks:
  postgres172_network_local:
    driver: bridge
